// eslint-disable-next-line @typescript-eslint/no-var-requires
const colors = require("tailwindcss/colors");

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/**/*.{js,jsx,ts,tsx,vue}",
        "./plugins/**/*.{js,jsx,ts,tsx,vue}",
    ],
    safelist: [
        "border-primary-600",
        "border-2",
        "text-primary-600",
        "fill-primary-600",
        "mr-8",
        "stroke-gray-400",
        "fill-gray-400",
        "bg-button-secondary",
        "bg-button-primary",
        "bg-button-info",
        "bg-button-disabled",
        "border-button-secondary",
        "border-button-primary",
        "border-button-info",
        "border-button-disabled",
        "text-button-secondary",
        "text-button-primary",
        "text-button-info",
        "text-button-disabled",
        "hover:bg-button-primary",
        "hover:bg-button-secondary",
        "hover:text-white",
        "hover:text-button-disabled",
        "hover:text-button-info",
        "hover:text-danger",
        "hover:bg-white",
        "hover:bg-danger",
        "hover:bg-button-info",
        "hover:bg-button-disabled",
    ],
    darkMode: "media",
    theme: {
        extend: {
            colors: {
                primary: {
                    DEFAULT: "#38927f",
                    50: "#f0f9f7",
                    100: "#ddf2ed",
                    200: "#bce4dc",
                    300: "#8cd0c4",
                    400: "#6BC3AE",
                    500: "#38927f",
                    600: "#2d7468",
                    700: "#266056",
                    800: "#224d47",
                    900: "#20403c",
                    950: "#0e2520",
                    light: "#6BC3AE", // legacy
                    lighter: "#ddf2ed", // for gradients
                    dark: "#006453", // legacy
                    card: "#DBE5E0",
                },
                button: {
                    primary: "#1BC47D",
                    secondary: "#6BC3AE",
                    info: "#00ADEE",
                    disabled: "#BABABA",
                },
                danger: {
                    DEFAULT: "#923838",
                    50: "#fef2f2",
                    100: "#fee2e2",
                    200: "#fecaca",
                    300: "#fca5a5",
                    400: "#f87171",
                    500: "#ef4444",
                    600: "#dc2626",
                    700: "#b91c1c",
                    800: "#991b1b",
                    900: "#7f1d1d",
                    light: "#EB7575",
                },
                success: {
                    DEFAULT: "#389256",
                    50: "#f0fdf4",
                    100: "#dcfce7",
                    200: "#bbf7d0",
                    300: "#86efac",
                    400: "#4ade80",
                    500: "#22c55e",
                    600: "#16a34a",
                    700: "#15803d",
                    800: "#166534",
                    900: "#14532d",
                    light: "#76BD7D",
                },
                warning: {
                    DEFAULT: "#f7a336",
                    50: "#fffbeb",
                    100: "#fef3c7",
                    200: "#fde68a",
                    300: "#fcd34d",
                    400: "#fbbf24",
                    500: "#f59e0b",
                    600: "#d97706",
                    700: "#b45309",
                    800: "#92400e",
                    900: "#78350f",
                },
                info: {
                    DEFAULT: "#00ADEE",
                    50: "#eff6ff",
                    100: "#dbeafe",
                    200: "#bfdbfe",
                    300: "#93c5fd",
                    400: "#60a5fa",
                    500: "#3b82f6",
                    600: "#2563eb",
                    700: "#1d4ed8",
                    800: "#1e40af",
                    900: "#1e3a8a",
                    light: "#EAAB7E",
                },
                internet: "#5F65FF",
                disabled: colors.gray["500"],
            },
        },
    },
    plugins: [],
};
